---
- name: install libselinux-python
  yum:
    name=libselinux-python
    state=present
  tags:
    - common
    - selinux

- name: disable selinux
  selinux: state=disabled
  tags:
    - common
    - selinux
