---
- name: set td-agent.conf
  blockinfile:
    dest: /etc/td-agent/td-agent.conf
    block: |
      <source>
        @type tail
        path /var/log/nginx/access.log
        #format nginx
        format /^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^ ]*) +\S*)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" "(?<forwarder>[^\"]*)")?/
        time_format %d/%b/%Y:%H:%M:%S %z
        pos_file /var/log/td-agent/nginx_access.log.pos
        tag nginx.access
      </source>
      <match nginx.access>
        @type forward
        host 192.168.33.12
        port 24224
        #flush_interval 1s
      </match>
    marker: "# {mark} NGINX ACCESS ANSIBLE MANAGED BLOCK"
  notify: restart fluentd
  tags:
    - fluentd
    - fluentd-client-nginx
