---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  tasks:
    - include: tasks/directory.yml
    - include: tasks/homebrew.yml
    - include: tasks/dotfiles.yml
    - include: tasks/tools.yml
