---
- name: install openjdk1.7
  yum: name=java-1.7.0-openjdk

- name: install rpm for rundeck
  yum: name=http://repo.rundeck.org/latest.rpm
  tags: rundeck

- name: install rundeck
  yum: name=rundeck
  tags: rundeck

- name: start rundeck and enabled at boot
  service:
    name=rundeckd
    state=started
    enabled=yes
  tags: rundeck
