---
- name: copy nginx.conf
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify: restart nginx
  tags: nginx

- name: copy {{ wordpress.host }}.conf
  template:
    src=wordpress.conf.j2
    dest=/etc/nginx/conf.d/{{ wordpress.host }}.conf
  notify: restart nginx
  tags: nginx

- name: change firewall rules
  firewalld:
    service: https
    permanent: true
    state: enabled
  notify: restart firewalld
  tags:
    - nginx

- name: create ssl directory
  file:
    path={{ item }}
    state=directory
  with_items:
    - /etc/nginx/ssl
  tags: nginx

- name: create tmp directory
  file:
    path={{ item }}
    state=directory
    mode=0775
    owner=nginx
    group={{ user.name }}
    recurse=yes
  with_items:
    - /var/tmp/nginx
  tags: nginx

- name: create document root directory
  file:
    path={{ item }}
    state=directory
    mode=0775
    owner=nginx
    group={{ user.name }}
  with_items:
    - /var/www/{{ wordpress.host }}
  tags: nginx
