---
# Prezto
- name: install Prezto
  git:
    repo: https://github.com/sorin-ionescu/prezto.git
    dest: ~/.zprezto
    update: no

- name: link in prezto files
  file:
    src: ~/.zprezto/runcoms/{{ item }}
    path: ~/.{{ item }}
    state: link
  with_items:
    - zlogin
    - zlogout
    - zprofile
    - zshenv
#    - zshrc

- name: link to preztorc
  file:
    src: ~/icloud/conf/dotfiles/.zpreztorc
    path: ~/.zpreztorc
    state: link

- name: Get docker-zsh-completion for Prezto
  get_url:
    url: https://raw.githubusercontent.com/felixr/docker-zsh-completion/master/_docker
    dest: ~/.zprezto/modules/completion/external/src/_docker
  tags: debug

# zsh
- name: is exists .zshrc.mac
  stat:
    path: ~/icloud/conf/dotfiles/.zshrc.mac
  register: f

- name: link .zshrc.mac
  file:
    src: ~/icloud/conf/dotfiles/.zshrc.mac
    dest: ~/.zshrc
    state: link
  when: f.stat.exists

# solarized
- name: clone Solarized
  git:
    repo: https://github.com/altercation/solarized.git
    dest: ~/var/lib/solarized

# Ricty
- name: clone RictyDiminished-for-Powerline
  git:
    repo: https://github.com/mzyy94/RictyDiminished-for-Powerline.git
    dest: ~/var/lib/RictyDiminished-for-Powerline

# NeoBundle
- name: clone NeoBundle
  git:
    repo: https://github.com/Shougo/neobundle.vim
    dest: ~/.vim/bundle/neobundle.vim
    update: no

# nodebrew
- name: create nodebrew directory
  file:
    path: ~/.nodebrew/src
    state: directory

# phpbrew
- name: download phpbrew
  get_url:
    url: https://github.com/phpbrew/phpbrew/raw/master/phpbrew
    dest: /usr/local/bin/phpbrew
    mode: 0755

- name: check if composer is installed
  stat:
    path: /usr/local/bin/composer
  register: f

- name: download composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
  when: not f.stat.exists

- name: run composer installer
  command: php composer-installer.php
  args:
    chdir: /tmp
  when: not f.stat.exists

- name: move composer into globally accessible location
  command: mv /tmp/composer.phar /usr/local/bin/composer
  when: not f.stat.exists

# Vagrant plugin
- name: regist list of vagrant plugin
  shell: "vagrant plugin list | awk '{print $1}'"
  register: f

- name: install vagrant plugin
  shell: "vagrant plugin install {{ item }}"
  with_items:
    - sahara
    - vagrant-cachier
    - vagrant-global-status
    - vagrant-omnibus
    - vagrant-vbguest
    - vagrant-vbox-snapshot
    - vagrant-global-status
    - vagrant-bindfs
  when: item not in f.stdout_lines

- name: update vagrant plugin
  shell: "vagrant plugin update {{ item }}"
  with_items:
    - sahara
    - vagrant-cachier
    - vagrant-global-status
    - vagrant-omnibus
    - vagrant-vbguest
    - vagrant-vbox-snapshot
    - vagrant-global-status
    - vagrant-bindfs
  when: item in f.stdout_lines
